### ISSUE TITLE
Cannot request 32bit Windows version via update/platform/version/stable

### ISSUE THREAD

**Issue by jamie-bell** [ArekSredzki/electron-release-server#45] opened 2016-06-23 22:44 UTC
I am either misunderstanding the documentation or this is not possible. Inside my Electron app, I know if I am ia32 or x64 and need auto-updates for the same architecture. I have tried combinations such as:

/update/win32/1.1.0/stable
/update/win64/1.1.0/stable
/update/windows_32/1.1.0/stable
/update/windows_64/1.1.0/stable

I understand that win32 is a common term for Windows platform in general but was going off of other posts I have read on here for possible solutions.

I have the following assets uploaded for v1.1.1 on the server:

app-1.1.1-full-ia32.nupkg
app-32bit.exe
app-1.1.1-full.nupkg
app.exe

All of my attempts have resulted in the 64bit version being served up to my auto update logic. Can anyone point me in the right direction or blatantly point out my stupidity? Thanks!

**Comment by ChrisK2** [comment] 2016-07-07 09:13
I have the same Issue.
I uploaded the 64 Bit version as
`odwebtvproplayer-0.1.4-full.nupkg` (54186123 bytes)
and the 32 Bit version as
`odwebtvproplayer-0.1.4-ia32-full.nupkg` (44243596 bytes).

however ...
```
$ curl http://SERVER/update/win64/0.1.3/RELEASES
19733B414AF1082991B8BD37465A84EC30ABF130 http://SERVER/download/0.1.4/odwebtvproplayer-0.1.4-full.nupkg 54186123

$ curl http://SERVER/update/win32/0.1.3/RELEASES
02D82B63812A82C2BCC6399217D966A4FDFAA541 http://SERVER/download/0.1.4/odwebtvproplayer-0.1.4-full.nupkg 44243596
```

The hash and the file size appear to be correct, yet the filename is always that of the 64 Bit update.

**Comment by ChrisK2** [comment] 2016-07-07 09:19
Okay, that was easy, for GOD KNOWS WHAT REASON, ['-ia32' gets stripped from the filename when the RELEASES file is generated](https://github.com/ArekSredzki/electron-release-server/blob/master/api/services/WindowsReleaseService.js#L114).

**Comment by jamiebell2678** [comment] 2016-07-07 15:58
Nice find @ChrisK2 - closing this issue.

**Comment by ChrisK2** [comment] 2016-07-07 16:52
wait, why close it? this is quite obviously unintended behavior and should be fixed.

**Comment by jamie-bell** [comment] 2016-07-07 16:55
valid point - busy day my bad. re-opening!

**Comment by ArekSredzki** [comment] 2016-07-07 17:02
@ChrisK2 @jamie-bell Removing `-ia32` is intentional. It *must* be removed from the filename provided in the `RELEASES` file as squirrel-windows (for god knows what reason) will parses it as part of the version number. As such, once it downloads and installs the update it'll see that it has the version without the -ia32 and downloads it again. So removing the `-ia32` is not the problem, that's important. The issue is that I look at the provided filename and use that to serve a file to the user (which you think would be fine, but isn't in this case). As such, another approach must be taken. Instead the file name must be ignored and the latest version for the specified platform (either `win32` or `win64`) should be served. (the platform should also be included in the download link mentioned in the `RELEASES` file.

**Comment by ArekSredzki** [comment] 2016-07-07 17:03
My time is very limited these days but I'll do my best to get to this tonight, unless you want to implement what I mentioned above and open a PR :)

**Comment by ArekSredzki** [comment] 2016-07-07 18:23
This is related to #17

**Comment by ArekSredzki** [comment] 2016-07-08 04:05
No progress on this today, hopefully tomorrow

**Comment by ChrisK2** [comment] 2016-07-08 07:05
I removed the `.replace()` from the server and updating on ia32 works perfectly fine so far. I guess Squirrel already fixed their version parsing?

On a similar note, maybe put the assets into different subfolders depending on platform to avoid naming collisions entirely?
Like:
```
http://SERVER/download/0.1.4/win32/odwebtvproplayer-0.1.4-full.nupkg
http://SERVER/download/0.1.4/win64/odwebtvproplayer-0.1.4-full.nupkg
```

**Comment by ArekSredzki** [comment] 2016-07-08 14:24
@ChrisK2 interesting, I'll look into this some more tonight.

I don't work on an electron project anymore so it's hard for me to do integration tests. Could you confirm that currently works on both architectures and on pre-release channels too?

I think I'll go with the naming scheme seen above either way (namespacing the platforms with a uri segment like you've shown) but it'd be good to know what Squirrel actually handles right now.

Thanks!

**Comment by ChrisK2** [comment] 2016-07-09 09:31
This is my very first electron project, so take my findings with a grain of salt, but I've been testing 32 and 64 bit updates intensively without problems (after removing the `replace()`, before the 32 bit app would download the 64bit update which wouldn't run on 32bit windows and effectively break the installation). However, I only tested using the stable release channel. I have my test-hardware at work so I can test using other channels only next week.

**Comment by ChrisK2** [comment] 2016-07-11 13:26
I did some more testing and now ran into the "endless updating" bug on a different machine. It works fine on Win10 Home English, but loops on Win10 Pro German ... maybe some weird locale problem. Anyway, name-spacing should "fix" (work around) this.

**Comment by cisso** [comment] 2016-07-11 15:24
@jamie-bell @ChrisK2 
what kind of app that make them? Linux support, Windows only?

**Comment by ArekSredzki** [comment] 2016-07-11 16:16
@cisso this issue only affects windows

**Comment by ArekSredzki** [comment] 2016-07-11 16:17
@ChrisK2 thanks for investigating! Did you test it on prereleases?

**Comment by ChrisK2** [comment] 2016-07-11 17:38
Just to be sure, you mean using the release-channels that squirrel supports, right? My app currently has no functionality for using channels, so I'll have to hardcode the test cases, but will do so tomorrow.

Looking forward to getting this properly fixed as I'd really like to use electron-release-server in production and renaming the 32bit update to something that doesn't break squirrel (`name_w32-x.y.z-full.nupkg` seems to be working) is slightly annoying during rapid testing.

**Comment by jamie-bell** [comment] 2016-07-11 17:40
@ChrisK2 @ArekSredzki  I finally got around to testing this patch and it seems to be correctly serving up the right file now but my 32bit Electron app gets into the 'infinite update loop' you referenced before. I'll be doing some more testing today to see if I can find any work-arounds. So far all I have done is remove the .replace(); I still have 'ia32' in the file name. Will try other combinations here shortly.

**Comment by ChrisK2** [comment] 2016-07-11 17:44
I couldn't find the Squirrel Code that parses the file-name, but it seems to be really dumb and simply slice the filename at the `-`, so everything that is stuck to the version-number or the full/delta or brings in additional `-` will break the file name parser. The only save way is appending something to the first part of the name using something like `_` like I stated above.

**Comment by jamie-bell** [comment] 2016-07-11 17:55
@ChrisK2 I came to the same conclusion based on your previous post. Was in the middle of uploading the 32bit nupkg as `name_w32-x.y.z-full.nupkg`. Using this convention in conjunction with the replace() being removed, everything seems to be correctly function now (on the STABLE channel).

**Closed** 2016-07-23 00:06 UTC
Labels: bug
