### ISSUE TITLE
Update file gets downloaded twice

### ISSUE THREAD

**Issue by karlpablo** [ArekSredzki/electron-release-server#125] opened 2017-02-24 19:47 UTC
I'm using a modified Skelektron template, which is pulling in updates from an electron release server instance.

Whenever I call autoUpdater.checkForUpdates() and there is an available update, the server takes a while to respond with "update-available". I've timed it to be the same duration it takes in between "update-available" and "update-downloaded", and the network logs show that it uses up the same amount of bandwidth.

However, if I try to go directly to the update feed URL via a browser, it only responds with a RELEASES file (which I think should be the correct behavior in the app).

Note: This is on Windows 10.

**Comment by kblum** [comment] 2017-09-29 14:41
I believe that the double update file download is happening because of an issue with how Electron calls the Squirrel updater: https://github.com/electron/electron/issues/5057

The fix for it was merged in on 2017/09/27 but has not been released yet: https://github.com/electron/electron/pull/10483

**Comment by BarryCarlyon** [comment] 2017-12-18 14:35
Confirmed. Squirrel downloads twice. Still does.

**Comment by jublo** [comment] 2018-04-19 15:33
@kblum 
> but has not been released yet: electron/electron#10483

Any idea when?

**Comment by ArekSredzki** [comment] 2019-10-07 02:06
Fixed externally

**Closed** 2019-10-07 02:06 UTC
